=== JoyOfCodingPDX/JoyOfCoding/projects-parent/projects/src/main/resources/edu/pdx/cs/joy/airline.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!-- DTD for describing an airline and its flights -->

<!-- An airline has a name and some number of flights -->
<!ELEMENT airline (name, flight*)>

<!ELEMENT name (#PCDATA)>

<!-- A flight has a number, a source, a departure time, a
     destination, an arrival time -->
<!ELEMENT flight (number, src, depart, dest, arrive)>

<!ELEMENT number (#PCDATA)>
<!ELEMENT src (#PCDATA)>
<!ELEMENT depart (date, time)>
<!ELEMENT dest (#PCDATA)>
<!ELEMENT arrive (date, time)>


<!-- A date has a month, day, and a year specified by Calendar.DATE,
     Calendar.MONTH, and Calendar.YEAR, respectfully. -->
<!ELEMENT date EMPTY>
<!ATTLIST date
          day    CDATA  #REQUIRED
          month  CDATA  #REQUIRED
          year   CDATA  #REQUIRED
>

<!-- A time has an hour, a minute, and at time zone.

     Hours are specified by ChronoField.HOUR_OF_DAY.

     Minutes are specified by ChronoField.MINUTE_OF_HOUR.

     The time zone is the name of the time zone such as "America/Los_Angeles"

-->
<!ELEMENT time EMPTY>
<!ATTLIST time
          hour       CDATA  #REQUIRED
          minute     CDATA  #REQUIRED
          time-zone  CDATA  #REQUIRED
>

=== JoyOfCodingPDX/JoyOfCoding/projects-parent/archetypes-parent/airline-archetype/src/main/resources/archetype-resources/src/test/resources/__packageInPathFormat__/valid-airline.xml
#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
<?xml version='1.0' encoding='us-ascii'?>

<!DOCTYPE airline
        PUBLIC "-//Joy of Coding at PSU//DTD Airline//EN" "airline.dtd">

<airline>
  <name>Valid Airlines</name>
  <flight>
    <number>1437</number>
    <src>BJX</src>
    <depart>
      <date day="25" month="9" year="2024"/>
      <time hour="17" minute="0"/>
    </depart>
    <dest>CMN</dest> <!-- They're taking me to Marrakesh! -->
    <arrive>
      <date day="26" month="9" year="2024"/>
      <time hour="3" minute="56"/>
    </arrive>
  </flight>
  <flight>
    <number>7865</number>
    <src>JNB</src>
    <depart>
      <date day="15" month="5" year="2024"/>
      <time hour="7" minute="24"/>
    </depart>
    <dest>XIY</dest>
    <arrive>
      <date day="16" month="5" year="2024"/>
      <time hour="9" minute="7"/>
    </arrive>
  </flight>
</airline>

=== JoyOfCodingPDX/JoyOfCoding/projects-parent/projects/src/main/java/edu/pdx/cs/joy/airline.xml
<?xml version='1.0' encoding='us-ascii'?>

<!-- A sample airline XML file -->
<!DOCTYPE airline
          SYSTEM "http://www.cs.pdx.edu/~whitlock/dtds/airline.dtd">

<airline>
  <name>Example Airlines</name>
  <flight>
    <number>1437</number>
    <src>BJX</src>
    <depart>
      <date day="25" month="9" year="2003"/>
      <time hour="17" minute="0"/>
    </depart>
    <dest>CMN</dest> <!-- They're taking me to Marrakesh! -->
    <arrive>
      <date day="26" month="9" year="2003"/>
      <time hour="3" minute="56"/>
    </arrive>
  </flight>
  <flight>
    <number>7865</number>
    <src>JNB</src>
    <depart>
      <date day="15" month="5" year="2003"/>
      <time hour="7" minute="24"/>
    </depart>
    <dest>XIY</dest>
    <arrive>
      <date day="16" month="5" year="2003"/>
      <time hour="9" minute="7"/>
    </arrive>
  </flight>
</airline>
