=== JoyOfCodingPDX/JoyOfCoding/projects-parent/projects/src/main/resources/edu/pdx/cs/joy/apptbook.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!-- DTD for describing an appointment book and the appointments it
     holds -->

<!-- An appointment book has an owner and some number of appointments -->
<!ELEMENT apptbook (owner, appt*)>

<!ELEMENT owner (#PCDATA)>

<!-- An appointment has a begin date/time, end date/time, and description -->
<!ELEMENT appt (begin, end, description)>

<!ELEMENT begin (date, time)>
<!ELEMENT end (date, time)>
<!ELEMENT description (#PCDATA)>

<!-- A date has a month, day, and a year specified by Calendar.DATE,
     Calendar.MONTH, and Calendar.YEAR, respectfully. -->
<!ELEMENT date EMPTY>
<!ATTLIST date
          day    CDATA  #REQUIRED
          month  CDATA  #REQUIRED
          year   CDATA  #REQUIRED
>

<!-- A time has an hour, a minute, and at time zone.

     Hours are specified by ChronoField.HOUR_OF_DAY.

     Minutes are specified by ChronoField.MINUTE_OF_HOUR.

     The time zone is the name of the time zone such as "America/Los_Angeles"

-->
<!ELEMENT time EMPTY>
<!ATTLIST time
          hour       CDATA  #REQUIRED
          minute     CDATA  #REQUIRED
          time-zone  CDATA  #REQUIRED
>

=== JoyOfCodingPDX/JoyOfCoding/projects-parent/projects/src/main/java/edu/pdx/cs/joy/apptbook.xml
<?xml version='1.0' encoding='us-ascii'?>

<!-- A sample appointment book XML file -->

<!DOCTYPE apptbook
          SYSTEM 'http://www.cs.pdx.edu/~whitlock/dtds/apptbook.dtd'>

<apptbook>
  <owner>Dave</owner>
  <appt>
    <begin>
      <date day="25" month="9" year="2000"/>
      <time hour="17" minute="0" time-zone="America/Los_Angeles"/>
    </begin>
    <end>
      <date day="25" month="9" year="2000"/>
      <time hour="17" minute="45" time-zone="America/Los_Angeles"/>
    </end>
    <description>Office hours at pizza place</description>
  </appt>
  <appt>
    <begin>
      <date day="25" month="9" year="2000"/>
      <time hour="18" minute="0" time-zone="America/Los_Angeles"/>
    </begin>
    <end>
      <date day="25" month="9" year="2000"/>
      <time hour="21" minute="30" time-zone="America/Los_Angeles"/>
    </end>
    <description>Keeping students awake in The Joy of Coding</description>
  </appt>
</apptbook>

=== JoyOfCodingPDX/JoyOfCoding/projects-parent/originals-parent/apptbook/src/test/resources/edu/pdx/cs410J/apptbook/valid-apptbook.xml
<?xml version='1.0' encoding='us-ascii'?>

<!DOCTYPE apptbook
          SYSTEM "http://www.cs.pdx.edu/~whitlock/dtds/apptbook.dtd">

<apptbook>
  <owner>Example Appointment Book</owner>
  <appt>
    <begin>
      <date day="11" month="10" year="2023"/>
      <time hour="13" minute="6" time-zone="America/Los_Angeles"/>
    </begin>
    <end>
      <date day="11" month="10" year="2023"/>
      <time hour="14" minute="0" time-zone="America/Los_Angeles"/>
    </end>
    <description>Example Appointment</description>
  </appt>
</apptbook>

=== JoyOfCodingPDX/JoyOfCoding/projects-parent/archetypes-parent/apptbook-archetype/src/main/resources/archetype-resources/src/test/resources/__packageInPathFormat__/valid-apptbook.xml
#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
<?xml version='1.0' encoding='us-ascii'?>

<!DOCTYPE apptbook
        PUBLIC "-//Joy of Coding at PSU//DTD Appointment Book//EN" "apptbook.dtd">

<apptbook>
  <owner>Example Appointment Book</owner>
  <appt>
    <begin>
      <date day="11" month="10" year="2023"/>
      <time hour="13" minute="6"/>
    </begin>
    <end>
      <date day="11" month="10" year="2023"/>
      <time hour="14" minute="0"/>
    </end>
    <description>Example Appointment</description>
  </appt>
</apptbook>
