=== JoyOfCodingPDX/JoyOfCoding/family/src/main/resources/edu/pdx/cs/joy/family/familytree.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!-- DTD for describing a family tree, people, and marriages -->

<!--
All Grade Book XML data must include a DOCTYPE of the following form:

  <!DOCTYPE family-tree PUBLIC
        "-//Portland State University//DTD CS410J Family Tree//EN"
        "http://www.cs.pdx.edu/~whitlock/dtds/familytree.dtd">

-->

<!-- A family tree consists of some number of people and some number
     of marriages -->
<!ELEMENT family-tree (person*, marriage*)>

<!-- A person consists of a required id and optional first, middle,
     and last name, date of birth, date of death, mother id, and 
     father id -->
<!ELEMENT person (first-name?, middle-name?, last-name?, dob?,
                  dod?, father-id?, mother-id?)>
<!ATTLIST person
   id     CDATA           #REQUIRED
   gender (male | female) #REQUIRED
>

<!-- These guys are just text -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT middle-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT father-id (#PCDATA)>
<!ELEMENT mother-id (#PCDATA)>

<!-- These guys are dates -->
<!ELEMENT dob (date)>
<!ELEMENT dod (date)>

<!-- Only a year is required -->
<!ELEMENT date (month?, day?, year)>

<!-- These guys are just numerical text.  Their values are determined
     by Calendar.MONTH, Calendar.DATE, and Calendar.YEAR -->
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT year (#PCDATA)>

<!-- A marriage has a husband id and wife id attributes, an optional
     date and location --> 
<!ELEMENT marriage (date?, location?)>
<!ATTLIST marriage
          husband-id  CDATA  #REQUIRED
          wife-id     CDATA  #REQUIRED
>

<!ELEMENT location (#PCDATA)>

=== JoyOfCodingPDX/JoyOfCoding/family/src/main/java/edu/pdx/cs/joy/family/davesFamily.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE family-tree PUBLIC "-//Portland State University//DTD CS410J Family Tree//EN" "http://www.cs.pdx.edu/~whitlock/dtds/familytree.dtd">
<family-tree>
<person id="3" gender="male">
<first-name>Stanley</first-name>
<middle-name>Jay</middle-name>
<last-name>Whitlock</last-name>
<dob>
<date>
<month>1</month>
<day>27</day>
<year>1948</year>
</date>
</dob>
</person>
<person id="2" gender="female">
<first-name>Carolyn</first-name>
<middle-name>Joyce</middle-name>
<last-name>Granger</last-name>
<dob>
<date>
<month>4</month>
<day>17</day>
<year>1945</year>
</date>
</dob>
</person>
<person id="1" gender="male">
<first-name>David</first-name>
<middle-name>Michael</middle-name>
<last-name>Whitlock</last-name>
<father-id>3</father-id>
<mother-id>2</mother-id>
</person>
<marriage husband-id="3" wife-id="2">
<date>
<month>6</month>
<day>12</day>
<year>1969</year>
</date>
<location>Durham, NH</location>
</marriage>
</family-tree>
