=== JoyOfCodingPDX/JoyOfCoding/projects-parent/projects/src/main/java/edu/pdx/cs/joy/phonebill.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!-- DTD for describing a phone bill and its phone calls -->

<!-- A phone bill has a customer and some number of phone calls -->
<!ELEMENT phone-bill (customer, call*)>

<!ELEMENT customer (#PCDATA)>

<!-- A phone call has caller's phone number, a callee's phone number,
     a start time and an end time -->
<!ELEMENT call (caller, callee, start, end)>

<!ELEMENT caller (#PCDATA)>
<!ELEMENT callee (#PCDATA)>
<!ELEMENT start (date, time)>
<!ELEMENT end (date, time)>

<!-- A date has a month, day, and a year specified by
     java.util.Calendar.DATE, Calendar.MONTH, and Calendar.YEAR,
     respectfully. --> 
<!ELEMENT date EMPTY>
<!ATTLIST date
          day    CDATA  #REQUIRED
          month  CDATA  #REQUIRED
          year   CDATA  #REQUIRED
>

<!-- A time has an hour and a minute.  Hours are specified by
     Calendar.HOUR_OF_DAY.  Minutes are specified by Calendar.MINUTE. -->
<!ELEMENT time EMPTY>
<!ATTLIST time
          hour    CDATA  #REQUIRED
          minute  CDATA  #REQUIRED
>

=== JoyOfCodingPDX/JoyOfCoding/projects-parent/projects/src/main/java/edu/pdx/cs/joy/phonebill.xml
<?xml version='1.0' encoding='us-ascii'?>

<!-- A sample phone bill XML file -->
<!DOCTYPE phone-bill
          SYSTEM "http://www.cs.pdx.edu/~whitlock/dtds/phonebill.dtd">
<phone-bill>
  <customer>Dave</customer>
  <call>
    <caller>503-245-2345</caller>
    <callee>607-777-1369</callee>
    <start>
      <date day="03" month="04" year="2002"/>
      <time hour="9" minute="56"/>
    </start>
    <end>
      <date day="03" month="04" year="2002"/>
      <!-- 43 minute call -->
      <time hour="10" minute="39"/>
    </end>
  </call>
  <call>
    <caller>603-868-1932</caller>
    <callee>765-497-8254</callee>
    <start>
      <date day="10" month="7" year="2002"/>
      <time hour="5" minute="27"/>
    </start>
    <end>
      <date day="10" month="7" year="2002"/>
      <time hour="6" minute="04"/>
    </end>
  </call>
</phone-bill>

=== JoyOfCodingPDX/JoyOfCoding/projects-parent/originals-parent/phonebill/src/test/resources/edu/pdx/cs/joy/phonebill/valid-phonebill.xml
<?xml version='1.0' encoding='us-ascii'?>

<!DOCTYPE phone-bill
          PUBLIC "-//Joy of Coding at PSU//DTD Phone Bill//EN" "phonebill.dtd">

<phone-bill>
  <customer>Dave</customer>
  <call>
    <caller>503-245-2345</caller>
    <callee>607-777-1369</callee>
    <start>
      <date day="03" month="04" year="2025"/>
      <time hour="9" minute="56"/>
    </start>
    <end>
      <date day="03" month="04" year="2025"/>
      <!-- 43 minute call -->
      <time hour="10" minute="39"/>
    </end>
  </call>
  <call>
    <caller>603-868-1932</caller>
    <callee>765-497-8254</callee>
    <start>
      <date day="10" month="7" year="2025"/>
      <time hour="5" minute="27"/>
    </start>
    <end>
      <date day="10" month="7" year="2025"/>
      <time hour="6" minute="04"/>
    </end>
  </call>
</phone-bill>
