=== JoyOfCodingPDX/JoyOfCoding/grader/src/main/resources/edu/pdx/cs/joy/grader/gradebook.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!-- A DTD for a grade book, students, and their grades -->

<!--
All Grade Book XML data must include a DOCTYPE of the following form:

  <!DOCTYPE gradebook PUBLIC
       "-//Portland State University//DTD CS410J Grade Book//EN"
       "http://www.cs.pdx.edu/~whitlock/dtds/gradebook.dtd">

-->

<!-- A grade book consists of the name of the class, the assignments
in the class, the ids of the students in the class, and an optional
number of late days allowed in the class -->
<!ELEMENT minimum-score (#PCDATA)>
<!ELEMENT maximum-score (#PCDATA)>
<!ELEMENT letter-grade-range EMPTY>
<!ATTLIST letter-grade-range
          letter-grade   CDATA  #REQUIRED
          minimum-score  CDATA  #REQUIRED
          maximum-score  CDATA  #REQUIRED
>
<!ELEMENT letter-grade-ranges (letter-grade-range+)>
<!ATTLIST letter-grade-ranges
          for-section (undergraduate | graduate) #IMPLIED
>
<!ELEMENT section-name (#PCDATA)>
<!ATTLIST section-name
          for-section (undergraduate | graduate) #IMPLIED
>
<!ELEMENT gradebook (name, assignments, letter-grade-ranges*, section-name*, students, lateDays?)>
<!ATTLIST gradebook
          crn CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT assignments (assignment*)>

<!ELEMENT students (id*)>

<!ELEMENT lateDays (#PCDATA)>

<!-- An assignment has a name, description, a required number of
points it is worth, a type, a due date, and some optional notes -->
<!ELEMENT assignment (name, description?, points, canvas-id?, due-date?, notes*)>
<!ATTLIST assignment
  type         (PROJECT | QUIZ | OTHER | POA | OPTIONAL)  #REQUIRED
  project-type (APP_CLASSES | TEXT_FILE | PRETTY_PRINT | KOANS | XML | REST | ANDROID)  #IMPLIED
>

<!ELEMENT description (#PCDATA)>
<!ELEMENT points (#PCDATA)>
<!ELEMENT due-date (#PCDATA)>

<!ELEMENT notes (note*)>
<!ELEMENT note (#PCDATA)>

<!-- A student has an id, first and last name, a nick name, email
address, social security number, a major, some grades, some late
assignments, and some notes -->
<!ELEMENT student (id, firstName?, lastName?, nickName?, email?, ssn?,
                   major?, canvas-id?, d2l-id?, letter-grade?, grades?, late?, resubmitted?, notes?)>
<!ATTLIST student
          enrolled-section (undergraduate | graduate) #IMPLIED
>

<!ELEMENT id (#PCDATA)>

<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT nickName (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT ssn (#PCDATA)>  <!-- xxx-xx-xxxx -->
<!ELEMENT major (#PCDATA)>
<!ELEMENT canvas-id (#PCDATA)>
<!ELEMENT d2l-id (#PCDATA)>
<!ELEMENT letter-grade (#PCDATA)>
<!ELEMENT grades (grade*)>
<!ELEMENT late (name*)>
<!ELEMENT resubmitted (name*)>

<!-- A grade has an assignment name, a score, submissions, and some notes -->
<!ELEMENT submission (#PCDATA)>
<!ELEMENT submissions (submission | submission-info)*>
<!ELEMENT grade (name, score, submissions?, notes?)>
<!ATTLIST grade
  type (INCOMPLETE | NO_GRADE) #IMPLIED
>

<!ELEMENT submission-info (date, estimated-hours?)>
<!ATTLIST submission-info
          late (true | false) "false"
>
<!ELEMENT date (#PCDATA)>
<!ELEMENT estimated-hours (#PCDATA)>

<!ELEMENT score (#PCDATA)>

=== JoyOfCodingPDX/JoyOfCoding/grader/src/test/resources/edu/pdx/cs/joy/grader/gradebook/studentWithD2LId.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE student PUBLIC "-//Portland State University//DTD CS410J Grade Book//EN" "http://www.cs.pdx.edu/~whitlock/dtds/gradebook.dtd">
<student enrolled-section="undergraduate">
<id>studentId</id>
<firstName>FirstName</firstName>
<lastName>LastName</lastName>
<email>email@email.edu</email>
<ssn>123456789</ssn>
<major>CS</major>
<d2l-id>D2L</d2l-id>
</student>

=== JoyOfCodingPDX/JoyOfCoding/grader/src/test/resources/edu/pdx/cs/joy/grader/gradebook/gradebookWithOldDTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE gradebook PUBLIC "-//Portland State University//DTD CS410J Grade Book//EN" "http://www.cs.pdx.edu/~whitlock/dtds/gradebook.dtd">
<gradebook>
<name>Summer 2021</name>
<assignments>
<assignment type="OTHER">
<name>Final 1</name>
<description>Final exam (written)</description>
<points>8.0</points>
<due-date>2021-08-11T18:00:00</due-date>
<notes/>
</assignment>
<assignment type="OTHER">
<name>Final 2</name>
<description>Final exam (group)</description>
<points>4.0</points>
<due-date>2021-08-11T23:00:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>Project1</name>
<description>Fundamental App Classes</description>
<points>6.0</points>
<due-date>2021-07-07T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>Project2</name>
<description>Text File</description>
<points>8.0</points>
<due-date>2021-07-14T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>Project3</name>
<description>Pretty Printing</description>
<points>9.0</points>
<due-date>2021-07-21T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>Project4</name>
<description>REST</description>
<points>12.0</points>
<due-date>2021-07-30T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>Project5</name>
<description>Mobile Application</description>
<points>14.0</points>
<due-date>2021-08-11T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>koans</name>
<description>Java koans</description>
<points>6.0</points>
<due-date>2021-07-21T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="OTHER">
<name>mobbing</name>
<description>Reflections on Mob Programming</description>
<points>3.5</points>
<due-date>2021-08-04T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="OTHER">
<name>pairing</name>
<description>Reflections on Pair Programming</description>
<points>3.5</points>
<due-date>2021-07-21T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="POA">
<name>poa1</name>
<description>POA for Project 1</description>
<points>1.0</points>
<due-date>2021-07-04T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="POA">
<name>poa2</name>
<description>POA for Project 2</description>
<points>1.0</points>
<due-date>2021-07-11T21:30:00</due-date>
<notes/>
</assignment>
<assignment type="POA">
<name>poa3</name>
<description>POA for Project 3</description>
<points>1.0</points>
<due-date>2021-07-18T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="POA">
<name>poa4</name>
<description>POA for Project 4</description>
<points>1.0</points>
<due-date>2021-07-25T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="POA">
<name>poa5</name>
<description>POA for Project 5</description>
<points>1.0</points>
<due-date>2021-08-08T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz1</name>
<description>Programming Background</description>
<points>3.0</points>
<due-date>2021-06-30T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz2</name>
<description>Java Language and OOP</description>
<points>3.0</points>
<due-date>2021-07-07T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz3</name>
<description>Language API</description>
<points>3.0</points>
<due-date>2021-07-14T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz4</name>
<description>Java IO and Collections</description>
<points>3.0</points>
<due-date>2021-07-21T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz5</name>
<description>Mid-term survey</description>
<points>3.0</points>
<due-date>2021-07-21T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz7</name>
<description>Android Development</description>
<points>3.0</points>
<due-date>2021-08-04T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz8</name>
<description>End-of-term Survey</description>
<points>3.0</points>
<due-date>2021-08-11T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>restquiz</name>
<description>Web and REST</description>
<points>3.0</points>
<due-date>2021-07-28T17:30:00</due-date>
<notes/>
</assignment>
</assignments>
<letter-grade-ranges for-section="undergraduate">
<letter-grade-range letter-grade="A" maximum-score="100" minimum-score="94"/>
<letter-grade-range letter-grade="A-" maximum-score="93" minimum-score="90"/>
<letter-grade-range letter-grade="B+" maximum-score="89" minimum-score="87"/>
<letter-grade-range letter-grade="B" maximum-score="86" minimum-score="83"/>
<letter-grade-range letter-grade="B-" maximum-score="82" minimum-score="80"/>
<letter-grade-range letter-grade="C+" maximum-score="79" minimum-score="77"/>
<letter-grade-range letter-grade="C" maximum-score="76" minimum-score="73"/>
<letter-grade-range letter-grade="C-" maximum-score="72" minimum-score="70"/>
<letter-grade-range letter-grade="D+" maximum-score="69" minimum-score="67"/>
<letter-grade-range letter-grade="D" maximum-score="66" minimum-score="63"/>
<letter-grade-range letter-grade="D-" maximum-score="62" minimum-score="60"/>
<letter-grade-range letter-grade="F" maximum-score="59" minimum-score="-10"/>
</letter-grade-ranges>
<letter-grade-ranges for-section="graduate">
<letter-grade-range letter-grade="A" maximum-score="100" minimum-score="94"/>
<letter-grade-range letter-grade="A-" maximum-score="93" minimum-score="90"/>
<letter-grade-range letter-grade="B+" maximum-score="89" minimum-score="87"/>
<letter-grade-range letter-grade="B" maximum-score="86" minimum-score="83"/>
<letter-grade-range letter-grade="B-" maximum-score="82" minimum-score="80"/>
<letter-grade-range letter-grade="C+" maximum-score="79" minimum-score="77"/>
<letter-grade-range letter-grade="C" maximum-score="76" minimum-score="73"/>
<letter-grade-range letter-grade="C-" maximum-score="72" minimum-score="70"/>
<letter-grade-range letter-grade="D+" maximum-score="69" minimum-score="67"/>
<letter-grade-range letter-grade="D" maximum-score="66" minimum-score="63"/>
<letter-grade-range letter-grade="D-" maximum-score="62" minimum-score="60"/>
<letter-grade-range letter-grade="F" maximum-score="59" minimum-score="-10"/>
</letter-grade-ranges>
<students/>
</gradebook>

=== JoyOfCodingPDX/JoyOfCoding/grader/src/test/resources/edu/pdx/cs/joy/grader/gradebook/gradebookWithoutProjectTypes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE gradebook PUBLIC "-//Portland State University//DTD CS410J Grade Book//EN" "http://www.cs.pdx.edu/~whitlock/dtds/gradebook.dtd">
<gradebook>
<name>Winter 2022</name>
<assignments>
<assignment type="OTHER">
<name>Final 1</name>
<description>Final Exam (Individual)</description>
<points>8.0</points>
<canvas-id>95635</canvas-id>
<due-date>2022-03-16T18:00:00</due-date>
<notes/>
</assignment>
<assignment type="OTHER">
<name>Final 2</name>
<description>Final Exam (Group)</description>
<points>4.0</points>
<canvas-id>95638</canvas-id>
<due-date>2022-03-16T23:00:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>Project1</name>
<description>Fundamental App Classes</description>
<points>5.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-01-19T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>Project2</name>
<description>Text File</description>
<points>6.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-01-26T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>Project3</name>
<description>Pretty Printing</description>
<points>7.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-02-02T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>Project4</name>
<description>XML</description>
<points>7.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-02-16T18:00:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>Project5</name>
<description>REST API</description>
<points>10.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-03-02T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>Project6</name>
<description>Mobile Application</description>
<points>13.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-03-16T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="PROJECT">
<name>koans</name>
<description>Java Koans</description>
<points>6.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-02-09T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="OTHER">
<name>mobbing</name>
<description>Reflections on Mob Programming</description>
<points>3.5</points>
<canvas-id>95637</canvas-id>
<due-date>2022-03-09T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="OTHER">
<name>pairing</name>
<description>Reflections on Pair Programming</description>
<points>3.5</points>
<canvas-id>95636</canvas-id>
<due-date>2022-02-16T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="POA">
<name>poa1</name>
<description>Project 1 POA</description>
<points>1.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-01-16T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="POA">
<name>poa2</name>
<description>POA for Project 2</description>
<points>1.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-01-23T21:30:00</due-date>
<notes/>
</assignment>
<assignment type="POA">
<name>poa3</name>
<description>POA for Project 3</description>
<points>1.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-01-30T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="POA">
<name>poa4</name>
<description>POA for Project 4</description>
<points>1.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-02-13T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="POA">
<name>poa5</name>
<description>POA for Project 5</description>
<points>1.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-02-27T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="POA">
<name>poa6</name>
<description>POA for Project 6</description>
<points>1.0</points>
<canvas-id>0</canvas-id>
<due-date>2022-03-13T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz1</name>
<description>Programming Background</description>
<points>3.0</points>
<canvas-id>95628</canvas-id>
<due-date>2022-01-12T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz2</name>
<description>Java Language and OOP</description>
<points>3.0</points>
<canvas-id>95629</canvas-id>
<due-date>2022-01-19T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz3</name>
<description>Language API</description>
<points>3.0</points>
<canvas-id>95630</canvas-id>
<due-date>2022-01-26T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz4</name>
<description>Java I/O and Collections</description>
<points>3.0</points>
<canvas-id>95631</canvas-id>
<due-date>2022-02-02T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz5</name>
<description>Midterm Survey</description>
<points>3.0</points>
<canvas-id>95626</canvas-id>
<due-date>2022-02-23T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz7</name>
<description>Android</description>
<points>3.0</points>
<canvas-id>95634</canvas-id>
<due-date>2022-03-09T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>quiz8</name>
<description>End of Term Survey</description>
<points>3.0</points>
<canvas-id>95625</canvas-id>
<due-date>2022-03-16T17:30:00</due-date>
<notes/>
</assignment>
<assignment type="QUIZ">
<name>restquiz</name>
<description>Web and REST</description>
<points>3.0</points>
<canvas-id>95632</canvas-id>
<due-date>2022-02-23T17:30:00</due-date>
<notes/>
</assignment>
</assignments>
<letter-grade-ranges for-section="undergraduate">
<letter-grade-range letter-grade="A" maximum-score="100" minimum-score="94"/>
<letter-grade-range letter-grade="A-" maximum-score="93" minimum-score="90"/>
<letter-grade-range letter-grade="B+" maximum-score="89" minimum-score="87"/>
<letter-grade-range letter-grade="B" maximum-score="86" minimum-score="83"/>
<letter-grade-range letter-grade="B-" maximum-score="82" minimum-score="80"/>
<letter-grade-range letter-grade="C+" maximum-score="79" minimum-score="77"/>
<letter-grade-range letter-grade="C" maximum-score="76" minimum-score="73"/>
<letter-grade-range letter-grade="C-" maximum-score="72" minimum-score="70"/>
<letter-grade-range letter-grade="D+" maximum-score="69" minimum-score="67"/>
<letter-grade-range letter-grade="D" maximum-score="66" minimum-score="63"/>
<letter-grade-range letter-grade="D-" maximum-score="62" minimum-score="60"/>
<letter-grade-range letter-grade="F" maximum-score="59" minimum-score="-10"/>
</letter-grade-ranges>
<letter-grade-ranges for-section="graduate">
<letter-grade-range letter-grade="A" maximum-score="100" minimum-score="94"/>
<letter-grade-range letter-grade="A-" maximum-score="93" minimum-score="90"/>
<letter-grade-range letter-grade="B+" maximum-score="89" minimum-score="87"/>
<letter-grade-range letter-grade="B" maximum-score="86" minimum-score="83"/>
<letter-grade-range letter-grade="B-" maximum-score="82" minimum-score="80"/>
<letter-grade-range letter-grade="C+" maximum-score="79" minimum-score="77"/>
<letter-grade-range letter-grade="C" maximum-score="76" minimum-score="73"/>
<letter-grade-range letter-grade="C-" maximum-score="72" minimum-score="70"/>
<letter-grade-range letter-grade="D+" maximum-score="69" minimum-score="67"/>
<letter-grade-range letter-grade="D" maximum-score="66" minimum-score="63"/>
<letter-grade-range letter-grade="D-" maximum-score="62" minimum-score="60"/>
<letter-grade-range letter-grade="F" maximum-score="59" minimum-score="-10"/>
</letter-grade-ranges>
<students/>
</gradebook>

=== JoyOfCodingPDX/JoyOfCoding/grader/src/test/resources/edu/pdx/cs/joy/grader/gradebook/studentWithSubmissionDatesAndNoSubmissionInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE student PUBLIC "-//Portland State University//DTD CS410J Grade Book//EN" "http://www.cs.pdx.edu/~whitlock/dtds/gradebook.dtd">
<student enrolled-section="graduate">
<id>studentId</id>
<firstName>FirstName</firstName>
<lastName>LastName</lastName>
<email>email@email.com</email>
<major>Major</major>
<grades>
<grade>
<name>Project2</name>
<score>8.0</score>
<submissions>
<submission>2021-07-15T14:32:33.180122476</submission>
<submission>2021-07-18T20:46:31.149349812</submission>
<submission>2021-07-18T21:07:10.470503273</submission>
</submissions>
</grade>
</grades>
<late>
<name>Project2</name>
<name>Project2</name>
<name>Project2</name>
</late>
</student>
